In [1]:
import torch

In [2]:
from torch.nn import functional as F
from torch import nn

tensor([[[[1., 2., 3.],
          [4., 5., 6.],
          [7., 8., 9.]]]], dtype=torch.float64,
       grad_fn=<ReshapeAliasBackward0>)

In [35]:
pool = nn.MaxPool1d(kernel_size=2, stride=2, dilation=1, return_indices=True)

In [36]:
input = torch.tensor([[[0, 1, 2, 3, 4], [5, 6, 7, 8, 9]],
                     [[10, 11, 12, 13, 14],[15,16,17,18,19]],
                      [[20,21,22,23,24],[25,26,27,28,29]]], dtype=torch.float64, requires_grad=True)
input.retain_grad()
input

tensor([[[ 0.,  1.,  2.,  3.,  4.],
         [ 5.,  6.,  7.,  8.,  9.]],

        [[10., 11., 12., 13., 14.],
         [15., 16., 17., 18., 19.]],

        [[20., 21., 22., 23., 24.],
         [25., 26., 27., 28., 29.]]], dtype=torch.float64, requires_grad=True)

In [37]:
output, indices = pool(input)

In [38]:
output

tensor([[[ 1.,  3.],
         [ 6.,  8.]],

        [[11., 13.],
         [16., 18.]],

        [[21., 23.],
         [26., 28.]]], dtype=torch.float64, grad_fn=<SqueezeBackward1>)

In [ ]:
unpool = nn.MaxUnpool1d(kernel_size=2, stride=2)
unpool(output, indices)

In [13]:
tensor([[[ 0.,  2.,  0.,  4.,  0.,  6.,  0., 8.]]])

# Example showcasing the use of output_size
input = torch.tensor([[[1., 2, 3, 4, 5, 6, 7, 8, 9]]])
output, indices = pool(input)
unpool(output, indices, output_size=input.size())
tensor([[[ 0.,  2.,  0.,  4.,  0.,  6.,  0., 8.,  0.]]])

unpool(output, indices)
tensor([[[ 0.,  2.,  0.,  4.,  0.,  6.,  0., 8.]]])

NameError: name 'tensor' is not defined